name: resdy_test
channels:
  - conda-forge
  - salilab
  - defaults
dependencies:
  - python=3.12
  - pip
  - biobox
  - biopython
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - Modeller
  - propka
  - ase
  - pytorch
  - torchani<=2.2.4
  - openmm
  - pdbfixer
  - msms
  - plotly
  - mdtraj
  - nglview
  - numba
  - python-dotenv
  - pip:
    - melodia-py==0.1.8
    - fair-esm
