name: Tests

on: [push]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-linux:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - uses: actions/checkout@v4

      - name: Set up conda
        env:
          KEY_MODELLER : ${{ secrets.KEY_MODELLER }}
        uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: resdy_test
          environment-file: .github/test_environment.yml
          conda-solver: libmamba
          channels: conda-forge,salilab
          channel-priority: strict
          auto-update-conda: false
          remove-profiles: true
          run-post: true
      - name: Test Uniprot
        run: |
          python test/test_uniprot.py
      - name: Test Alphafold
        run: |
          python test/test_alphafold.py
      - name: Test Helper
        run: |
          python test/test_helper.py
      - name: Test Measure
        run: |
          python test/test_measure.py
      - name: Test Aggregation
        run: |
          python test/test_aggregate.py
      - name: Test Analysis
        run: |
          python test/test_analysis.py
      - name: Test Protein
        run: |
          python test/test_protein.py
      - name: Test Patcher
        run: |
          python test/test_patcher.py
