name: Tests

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - uses: actions/checkout@v4

      - name: Set up conda + mamba
        env:
          KEY_MODELLER : ${{ secrets.KEY_MODELLER }}
        uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: cpn_test
          environment-file: .github/test_environment.yml
          mamba-version: '*'
          conda-solver: libmamba
          channels: conda-forge,salilab,defaults
          channel-priority: strict
          auto-update-conda: false
          remove-profiles: true
          run-post: true
      - name: Test
        run: |
          python test/test_uniprot.py
          python test/test_alphafold.py
          python test/test_helper.py
          python test/test_measure.py
          python test/test_aggregate.py
          python test/test_analysis.py
          python test/test_protein.py
          python test/test_patcher.py
